permalink: pretty
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass"]

title: Austin.RB
url: http://austinrb.org
email: ttyrrell+austinrb@gmail.com
meeting:
  when:
    date: "Saturday, August 11"
    time: "TBA"
    url: "http://blog.context.io/2012/08/announcing-the-lsrc-overnight-hackathon-in-austin-texas-august-11th/"
  where:
    location: "Capital Factory"
    url: "http://www.capitalfactory.com/"
