permalink: pretty
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass"]

title: Austin.RB
url: http://austinrb.org
email: info@austinrb.org
meeting:
  when:
    date: "Tuesday, January 17"
    time: "7:00-9:00PM"
    url: "http://plancast.com/p/9c8c"
  where:
    location: "CoSpace"
    url: "http://cospaceatx.com/"
