title: Austin.RB
url: http://austinrb.org
email: info@austinrb.org
meeting:
  when:
    date: "Tuesday, November 15"
    time: "7:30-9:30PM"
    url: "http://plancast.com/p/88db"
  where:
    location: "Cospace"
    url: "http://maps.google.com/maps/place?client=safari&rls=en&oe=UTF-8&um=1&ie=UTF-8&q=Cospace&fb=1&gl=us&hq=cospace&hnear=0x8644b599a0cc032f:0x5d9b464bd469d57a,Austin,+TX&cid=5698450083142754163&ei=SiuLTp_sB4uBsgKOnpnGBA&sa=X&oi=local_result&ct=map-marker-link&resnum=1&ved=0CDkQrwswAA"