title: Austin.RB
url: http://austinrb.org
email: info@austinrb.org
meeting:
  when:
    date: "Thursday, July 21"
    time: "7-9PM"
    url: http://plancast.com/p/6edf
  where:
    location: "Norris Conference Center - Austin"
    url: "http://maps.google.com/maps/place?client=safari&rls=en&oe=UTF-8&um=1&ie=UTF-8&q=norris+conference+center+austin&fb=1&gl=us&hq=norris+conference+center&hnear=Austin,+TX&cid=6576048118745809585"