title: Austin.RB
url: http://austinrb.org
email: info@austinrb.org
meeting:
  when:
    date: "Thursday, September 15"
    time: "8-11PM"
    url: http://plancast.com/p/7isu
  where:
    location: "Ginger Man"
    url: "http://maps.google.com/maps?client=safari&rls=en&q=ginger+man+austin&oe=UTF-8&um=1&ie=UTF-8&sa=N&hl=en&tab=wl"