permalink: pretty
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass"]

title: Austin.RB
url: http://austinrb.org
email: info@austinrb.org
meeting:
  when:
    date: "Tuesday, December 13"
    time: "7:00-9:00PM"
    url: "http://www.refreshaustin.org/bash/"
  where:
    location: "Austin Web Bash - Buffalo Billiards"
    url: "http://maps.google.com/maps/place?oe=UTF-8&ie=UTF8&q=buffalo+billiards+austin&fb=1&gl=us&hq=buffalo+billiards&hnear=0x8644b599a0cc032f:0x5d9b464bd469d57a,Austin,+TX&cid=14795740990854888209&t=m&z=14"